version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12.7  # Docker image as executor
    steps:
      - checkout
      - run:
          name: Install dependencies and run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install ".[dev]"

            # Run unit tests.
            pytest -v amazon_seg_project_tests/test_unit

            # Run integration tests.
            pytest -v amazon_seg_project_tests/test_integration

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: AWS_access
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
