version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12.4  # Example using a Python image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python --version
            pip install --upgrade pip
            pip install -e ".[dev]"
            echo $AWS_REGION_NAME
      - run:
          name: Run tests
          command: |
            pytest

  build:
    docker:
      - image: cimg/python:3.12.4  
    steps:
      - checkout
      - run:
          name: Build artifact
          command: |
            echo "Building artifact..."
            # Replace with actual build commands if needed

  deploy:
    docker:
      - image: cimg/python:3.12.4
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # Replace with actual deployment commands if needed

workflows:
  version: 2
  example:
    jobs:
      - test:
          context: AWS_access
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
