version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12.7  # Use Python 3.12.7 Docker image as executor.
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python --version
            pip install --upgrade pip
            pip install -e ".[dev]"
      - run:
          name: Run tests
          command: |
            # Run unit tests first.
            pytest -v amazon_seg_project_tests/test_unit
            # Next, execute integration tests.
            pytest -v amazon_seg_project_tests/test_integration

  build:
    docker:
      - image: cimg/python:3.12.7
    steps:
      - checkout
      - run:
          name: Build artifact
          command: |
            echo "Building artifact..."
            # Replace with actual build commands if needed

  deploy:
    docker:
      - image: cimg/python:3.12.7
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # Replace with actual deployment commands if needed

workflows:
  version: 2
  example:
    jobs:
      - test:
          context: AWS_access
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
      - build:
          requires:
            - test
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
