version: 2.1

orbs:
  python: circleci/python@3.0.0

jobs:
  build:
    executor:
      name: python/default
      tag: "3.12.7"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python --version
            pip install --upgrade pip
            pip install -e ".[dev]"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    executor:
      name: python/default
      tag: "3.12.7"
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: |
            # Run unit tests first.
            pytest -v amazon_seg_project_tests/test_unit
            # Next, execute integration tests.
            # pytest -v amazon_seg_project_tests/test_integration

  deploy:
    executor:
      name: python/default
      tag: "3.12.7"
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # Replace with actual deployment commands if needed

workflows:
  version: 2
  example:
    jobs:
      - build:
          context: AWS_access
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
      - test:
          context: AWS_access
          requires:
            - build
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
      - deploy:
          context: AWS_access
          requires:
            - build
            - test
          filters:
            branches:
              only:  # Only branches matching the below regex filters will run.
                - dagster
